linters-settings:
  depguard:
    rules:
      main:
        deny:
          - pkg: flag
            desc: "Use github.com/namsral/flag instead."
          - pkg: github.com/tehsphinx/dbg
            desc: "Should only be used for debugging."
          - pkg: github.com/bmizerany/assert
            desc: "Use github.com/matryer/is or github.com/stretchr/testify/assert instead."
  funlen:
    lines: 70
    statements: 40
  gci:
    sections:
      - standard
      - default
      - prefix(gitlab.com/dabnis)
  gocyclo:
    min-complexity: 20
  govet:
    check-shadowing: true
  lll:
    line-length: 150
  maintidx:
    under: 40
  maligned:
    suggest-new: true
  nakedret:
    max-func-lines: 0
  nolintlint:
    require-specific: true
  revive:
    confidence: 0.1
    rules:
      - name: exported
        severity: warning
        disabled: false
  stylecheck:
    http-status-code-whitelist: []
  usestdlibvars:
    time-month: true
    time-layout: true
    crypto-hash: true
    default-rpc-path: true
    os-dev-null: true
    sql-isolation-level: true
    tls-signature-scheme: true
    constant-kind: true
    syslog-priority: true
  whitespace:
    multi-func: true
  wrapcheck:
    ignorePackageGlobs:
      - github.com/tehsphinx/errs
      - gitlab.com/dabnis-project/*
      - storj.io/drpc/drpcerr

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - decorder
    - depguard
    - dogsled
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goerr113
    - gofmt
    - gofumpt
    - goimports
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - gosmopolitan
    - govet
    - importas
    - ineffassign
    - lll
    - maintidx
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nosprintfhostport
    - prealloc
    - predeclared
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagalign
    - tagliatelle
    - tenv
    - testableexamples
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    - wrapcheck

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - errcheck
        - forcetypeassert
        - gocritic
        - gocyclo
        - gosec
        - maintidx
        - prealloc
    - text: "Using the variable on range scope `tt` in function literal"
      linters:
        - scopelint

  exclude-use-default: false
  exclude:
    # errcheck: Almost all programs ignore errors on these functions and in most cases it's ok
    - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked
